### Question 1: Array Creation and Manipulation

In [1]:
import numpy as np

In [2]:
# Q1.1: Create a 4x4 identity matrix using np.eye()
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
# Q1.2: Create an array of 8 zeros using np.zeros()
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Q1.3: Create an array of 6 ones using np.ones()
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

### Question 2: Array Attributes and Information

In [7]:
# Q2.1: What is the shape of the banking_data array?

banking_data = np.array([
    # Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])
banking_data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [8]:
# Q2.2: What is the data type of the banking_data array?
banking_data.dtype

dtype('int64')

In [9]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
banking_data.size

50

In [10]:
# Q2.4: What is the number of dimensions of the banking_data array?
banking_data.ndim

2

In [11]:
# Q2.5: What is the memory size of the banking_data array in bytes?
banking_data.nbytes

400

### Question 3: Indexing and Slicing

In [12]:
# Q3.1: Extract the first row of banking_data
banking_data[0]

array([    1, 25000,   300,  1200,    10])

In [13]:
# Q3.2: Extract the last row of banking_data
banking_data[-1]

array([   10, 33000,   410,  1450,    11])

In [14]:
# Q3.3: Extract the Account_Balance column (column index 1)
banking_data[:,1:2]

array([[25000],
       [32000],
       [28000],
       [41000],
       [35000],
       [27000],
       [39000],
       [30000],
       [45000],
       [33000]])

In [15]:
# Q3.4: Extract the first 4 rows and first 3 columns
banking_data[0:4,0:3]

array([[    1, 25000,   300],
       [    2, 32000,   450],
       [    3, 28000,   380],
       [    4, 41000,   500]])

In [16]:
# Q3.5: Extract rows 3 to 7 (inclusive)
banking_data[3:7]

array([[    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18]])

### Question 4: Mathematical Operations

In [17]:
# Q4.1: Calculate the sum of all account balances
banking_data[:,1:2].sum()

np.int64(335000)

In [18]:
sum_account=np.sum(banking_data[:,1])
sum_account

np.int64(335000)

# Q4.2: Calculate the mean account balance
banking_data[:,1:2].mean()

In [19]:
# Q4.3: Calculate the standard deviation of account balances
banking_data[:,1:2].std()

np.float64(6168.468205316454)

In [20]:
# Q4.4: Calculate the variance of account balances
banking_data[:,1:2].var()

np.float64(38050000.0)

In [21]:
# Q4.5: Calculate the median account balance
import numpy as np
np.median(banking_data[:,1])

np.float64(32500.0)

### Question 5: Statistical Functions

In [22]:
# Q5.1: Find the minimum and maximum account balances
banking_data[:,1:2].min()


np.int64(25000)

In [23]:
banking_data[:,1:2].max()

np.int64(45000)

In [24]:
# Q5.2: Find the minimum and maximum credit scores
banking_data[:,2:3].min()

np.int64(300)

In [25]:
banking_data[:,2:3].max()

np.int64(550)

In [26]:
#GPT
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
import numpy as np

# Extract Account_Balance column
account_balance = banking_data[:, 1]

# Calculate 25th, 50th, 75th percentiles
percentile=np.quantile(account_balance,[0.25,0.5,0.75])
percentile

array([28500., 32500., 38000.])

In [27]:
#GPT
# Q5.4: Calculate the correlation between account balance and credit score
import numpy as np

# Extract columns
account_balance = banking_data[:,1]
credit_score = banking_data[:,2]

# Calculate correlation
correlation_matrix = np.corrcoef(account_balance, credit_score)
correlation = correlation_matrix[0, 1]
print("Correlation:", correlation)

Correlation: 0.9593636912502479


In [28]:
#GPT
# Q5.5: Calculate the covariance between account balance and credit score
import numpy as np

# Extract columns
account_balance = banking_data[:, 1]
credit_score = banking_data[:, 2]

# Calculate covariance
cov_matrix = np.cov(account_balance, credit_score, ddof=0)  # population covariance
covariance = cov_matrix[0, 1]
print("Covariance:", covariance)

Covariance: 408500.0


### Question 6: Array Reshaping and Manipulation

In [29]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
banking_data.reshape(5,10)

array([[    1, 25000,   300,  1200,    10,     2, 32000,   450,  1500,
           15],
       [    3, 28000,   380,  1100,     8,     4, 41000,   500,  1600,
           20],
       [    5, 35000,   420,  1400,    12,     6, 27000,   360,  1300,
            9],
       [    7, 39000,   480,  1700,    18,     8, 30000,   400,  1250,
           14],
       [    9, 45000,   550,  1800,    25,    10, 33000,   410,  1450,
           11]])

In [30]:
# Q6.2: Flatten the banking_data to a 1D array
    #Flattening means converting a multi-dimensional array (like 2D or 3D) into a 1D array
banking_data.flatten()

array([    1, 25000,   300,  1200,    10,     2, 32000,   450,  1500,
          15,     3, 28000,   380,  1100,     8,     4, 41000,   500,
        1600,    20,     5, 35000,   420,  1400,    12,     6, 27000,
         360,  1300,     9,     7, 39000,   480,  1700,    18,     8,
       30000,   400,  1250,    14,     9, 45000,   550,  1800,    25,
          10, 33000,   410,  1450,    11])

In [31]:
# Q6.3: Transpose the banking_data
banking_data.transpose()

array([[    1,     2,     3,     4,     5,     6,     7,     8,     9,
           10],
       [25000, 32000, 28000, 41000, 35000, 27000, 39000, 30000, 45000,
        33000],
       [  300,   450,   380,   500,   420,   360,   480,   400,   550,
          410],
       [ 1200,  1500,  1100,  1600,  1400,  1300,  1700,  1250,  1800,
         1450],
       [   10,    15,     8,    20,    12,     9,    18,    14,    25,
           11]])

In [32]:
# Q6.4: Split the banking_data into 2 equal parts vertically
import numpy as np
split_data=np.vsplit(banking_data,2)
split_data

[array([[    1, 25000,   300,  1200,    10],
        [    2, 32000,   450,  1500,    15],
        [    3, 28000,   380,  1100,     8],
        [    4, 41000,   500,  1600,    20],
        [    5, 35000,   420,  1400,    12]]),
 array([[    6, 27000,   360,  1300,     9],
        [    7, 39000,   480,  1700,    18],
        [    8, 30000,   400,  1250,    14],
        [    9, 45000,   550,  1800,    25],
        [   10, 33000,   410,  1450,    11]])]

In [109]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
# import numpy as np
# split_data=np.hsplit(banking_data,2)
# split_data


#Here we will get error beacuse there are 5 columns, 5 columns will not divide equally so we get error.

### Question 7: Logical Operations and Filtering

In [34]:
# Q7.1: Find customers with account balance greater than $100,000
data=banking_data[banking_data[:,1]>100000]
data

array([], shape=(0, 5), dtype=int64)

In [35]:
# Q7.2: Find customers with credit score greater than 800
data=banking_data[banking_data[:,2]>800]
data

array([], shape=(0, 5), dtype=int64)

In [36]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
data=banking_data[(banking_data[:,3]>50) & (banking_data[:,2]<750 )]
data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [37]:
#GPT
# Q7.4: Count how many customers have account balance between $10,000 and $100,000

import numpy as np

# Filter condition: 10,000 < Account_Balance < 100,000
condition = (banking_data[:, 1] > 10000) & (banking_data[:, 1] < 100000)

# Apply condition and count rows
count = np.sum(condition)
print("Number of customers with balance between $10,000 and $100,000:", count)

Number of customers with balance between $10,000 and $100,000: 10


In [38]:
# Q7.5: Find the index of the customer with the highest credit score
import numpy as np

# Find the index of the max credit score (column index 2)
max_credit_index = np.argmax(banking_data[:, 2])
print("Index of customer with highest credit score:", max_credit_index)

Index of customer with highest credit score: 8


### Question 8: Sorting and Searching

In [39]:
# Q8.1: Sort the banking_data by account balance (ascending)
import numpy as np

banking_data[:,1][::-1]

array([33000, 45000, 30000, 39000, 27000, 35000, 41000, 28000, 32000,
       25000])

In [40]:
# Q8.2: Sort the banking_data by credit score (descending)
import numpy as np

sorting=banking_data[banking_data[:,2].argsort()][::-1]   #.argsort used to sort the column data.
print(sorting)

[[    9 45000   550  1800    25]
 [    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    2 32000   450  1500    15]
 [    5 35000   420  1400    12]
 [   10 33000   410  1450    11]
 [    8 30000   400  1250    14]
 [    3 28000   380  1100     8]
 [    6 27000   360  1300     9]
 [    1 25000   300  1200    10]]


In [41]:
# Q8.3: Find the indices that would sort the array by years active
import numpy as np

sorting = banking_data[banking_data[:,-1].argsort()]
sorting

array([[    3, 28000,   380,  1100,     8],
       [    6, 27000,   360,  1300,     9],
       [    1, 25000,   300,  1200,    10],
       [   10, 33000,   410,  1450,    11],
       [    5, 35000,   420,  1400,    12],
       [    8, 30000,   400,  1250,    14],
       [    2, 32000,   450,  1500,    15],
       [    7, 39000,   480,  1700,    18],
       [    4, 41000,   500,  1600,    20],
       [    9, 45000,   550,  1800,    25]])

In [42]:
# Q8.4: Find the customer with the second highest account balance
import numpy as np

#gives account column
acc_balance = banking_data[:,1]

#sort the account balance
sort_balance = np.sort(acc_balance)[::-1]

#gets 2nd hightes values in account balance column
second_high = sort_balance[1]
print(second_high)

41000


In [43]:
# Q8.5: Find the customer with the lowest transaction count
import numpy as np

tran_count = banking_data[:,-2]
sort_transaction = np.sort(tran_count)[::-1]
lowerst_trans = sort_transaction[-1]
print(lowerst_trans)

1100


### Question 9: Mathematical Functions

In [44]:
# Q9.1: Calculate the absolute values of all elements
import numpy as np

ab = np.abs(banking_data)
print(ab)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [45]:
# Q9.2: Calculate the square root of all account balances
import numpy as np

sq=np.sqrt(banking_data[:,1])
sq

array([158.11388301, 178.8854382 , 167.33200531, 202.48456731,
       187.08286934, 164.31676725, 197.48417658, 173.20508076,
       212.13203436, 181.65902125])

In [46]:
# Q9.3: Calculate the square of all credit scores
import numpy as np

sq = np.sqrt(banking_data[:,2])
print(sq)

[17.32050808 21.21320344 19.49358869 22.36067977 20.49390153 18.97366596
 21.9089023  20.         23.4520788  20.24845673]


In [47]:
# Q9.4: Calculate the exponential of all transaction counts
import numpy as np

ex = np.exp(banking_data[:,3])
print(ex)

[inf inf inf inf inf inf inf inf inf inf]


C:\Users\Subhash G\AppData\Local\Temp\ipykernel_33664\772549311.py:4: RuntimeWarning: overflow encountered in exp
  ex = np.exp(banking_data[:,3])


In [48]:
# Q9.5: Calculate the natural logarithm of all account balances
import numpy as np

algo = np.log(banking_data[:,1])
print(algo)

[10.1266311  10.37349118 10.23995979 10.62132735 10.46310334 10.20359214
 10.57131693 10.30895266 10.71441777 10.40426284]


### Question 10: Advanced Operations

In [49]:
# Q10.1: Calculate the cumulative sum of account balances
import numpy as np

cum = np.cumsum(banking_data[:,1])
print(cum)


[ 25000  57000  85000 126000 161000 188000 227000 257000 302000 335000]


In [50]:
# Q10.2: Calculate the cumulative product of transaction counts
import numpy as np

cump = np.cumprod(banking_data[:,3])
print(cump)


[                1200              1800000           1980000000
        3168000000000     4435200000000000  5765760000000000000
  6570896860228091904  4819962484364410880  5962757212450324480
 -5525012516809211904]


In [51]:
# Q10.3: Calculate the difference between consecutive account balances
import numpy as np

cons = np.cos(banking_data[:,1])
print(cons)


[ 0.70075771  0.9656743  -0.52734684 -0.60125783 -0.88525532  0.40598946
  0.96409072 -0.59642953  0.9850435   0.7578619 ]


In [52]:
# Q10.4: Calculate the gradient of account balances
import numpy as np

grad = np.gradient(banking_data[:,1])
print(grad)


[  7000.   1500.   4500.   3500.  -7000.   2000.   1500.   3000.   1500.
 -12000.]


In [53]:
# Q10.5: Calculate the histogram of account balances with 5 bins
import numpy as np

hist = np.histogram(banking_data[:,1],5)
print(hist)


(array([3, 2, 2, 1, 2]), array([25000., 29000., 33000., 37000., 41000., 45000.]))


### Question 11: Random Numbers and Simulation

In [54]:
# Q11.1: Generate 6 random integers between 1 and 1000

import numpy as np

rand=np.random.randint(1,1000,6)
print(rand)

[ 79 712 291   8 482 258]


In [55]:
# Q11.2: Generate 6 random floats between 0 and 1

import numpy as np
rand=np.random.rand(6)
print(rand)

[0.40695477 0.27915712 0.84185401 0.09777991 0.75660982 0.65191186]


In [56]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)

import numpy as np
rand = np.random.normal(700, 100, 6)
print(rand)


[763.76007795 705.00601858 795.54559456 505.92394254 810.6119921
 736.04662558]


In [57]:
# Q11.4: Shuffle the banking_data rows randomly
import numpy as np
np.random.shuffle(banking_data)
banking_data

array([[    3, 28000,   380,  1100,     8],
       [   10, 33000,   410,  1450,    11],
       [    2, 32000,   450,  1500,    15],
       [    7, 39000,   480,  1700,    18],
       [    1, 25000,   300,  1200,    10],
       [    8, 30000,   400,  1250,    14],
       [    6, 27000,   360,  1300,     9],
       [    9, 45000,   550,  1800,    25],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12]])

In [58]:
# Q11.5: Set random seed to 123 and generate 4 random numbers
import numpy as np
np.random.seed(123)
rand_seed=np.random.rand(4)
print(rand_seed)

[0.69646919 0.28613933 0.22685145 0.55131477]


### Question 12: Linear Algebra Operations

In [59]:
# Q12.1: Calculate the dot product of account balance and credit score columns
import numpy as np

# Using slicing to select columns
account_balance = banking_data[:, 1]  # Second column
credit_score = banking_data[:, 2]     # Third column

# Calculate dot product
dot_product = np.dot(account_balance, credit_score)

print(dot_product)

146460000


In [60]:
# Q12.2: Calculate the cross product of first two rows

import numpy as np
row1 = banking_data[0][:3]
row2 = banking_data[1][:3]
cross_product = np.cross(row1,row2)
print(cross_product)

[-1060000     2570  -181000]


In [61]:
# Q12.3: Calculate the norm (magnitude) of the account balance column

import numpy as np
account_balance = banking_data[:, 1]                     # Select Account_Balance column (second column)
norm_account_balance = np.linalg.norm(account_balance)   # Calculate the norm (magnitude)
print("Norm (magnitude) of Account Balance column:", norm_account_balance)

Norm (magnitude) of Account Balance column: 107717.22239270747


In [62]:
# Q12.4: Create a 3x3 matrix and calculate its determinant

import numpy as np

# Create a 3x3 matrix
matrix = np.array([
    [2, 5, 3],
    [1, -2, -1],
    [1, 3, 4]
])

# Calculate determinant
determinant = np.linalg.det(matrix)

print("3x3 Matrix:")
print(matrix)
print("\nDeterminant of the matrix:", determinant)


3x3 Matrix:
[[ 2  5  3]
 [ 1 -2 -1]
 [ 1  3  4]]

Determinant of the matrix: -20.000000000000007


In [63]:
# Q12.5: Calculate the inverse of the 3x3 matrix
import numpy as np

# Create a 3x3 matrix
matrix = np.array([
    [2, 5, 3],
    [1, -2, -1],
    [1, 3, 4]
])

# Calculate the inverse
inverse_matrix = np.linalg.inv(matrix)

print("3x3 Matrix:")
print(matrix)
print("\nInverse of the matrix:")
print(inverse_matrix)

3x3 Matrix:
[[ 2  5  3]
 [ 1 -2 -1]
 [ 1  3  4]]

Inverse of the matrix:
[[ 0.25  0.55 -0.05]
 [ 0.25 -0.25 -0.25]
 [-0.25  0.05  0.45]]


### Question 13: String Operations

In [64]:
# Q13.1: Convert all customer IDs to strings
import numpy as np
# Convert Customer_ID column (first column) to strings
customer_ids_str = banking_data[:, 0].astype(str)

print("Customer IDs as strings:", customer_ids_str)

Customer IDs as strings: ['3' '10' '2' '7' '1' '8' '6' '9' '4' '5']


In [68]:
# Q13.2: Check if any customer ID contains '100'
data = np.char.find(customer_ids_str, '100') >= 0
print(banking_data[data])


[]


In [70]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
data = np.char.upper(customer_ids_str)
print(data)

['3' '10' '2' '7' '1' '8' '6' '9' '4' '5']


In [71]:
# Q13.4: Count the length of each customer ID string
data = np.char.str_len(customer_ids_str)
print(data)

[1 2 1 1 1 1 1 1 1 1]


In [72]:
# Q13.5: Replace '10' with 'CUST' in customer IDs
data = np.char.replace(customer_ids_str, '10', 'CUST')
print(data)

['3' 'CUST' '2' '7' '1' '8' '6' '9' '4' '5']


### Question 14: Date and Time Operations

In [73]:
# Q14.1: Convert years active to months
yrs_to_months = banking_data[:, 4] * 12
print(yrs_to_months)

[ 96 132 180 216 120 168 108 300 240 144]


In [74]:
# Q14.2: Calculate the average years active
avg_yrs = np.mean(banking_data[:, 4])
print(avg_yrs)

14.2


In [75]:
# Q14.3: Find customers who have been active for more than 15 years
yrs_active = banking_data[banking_data[:, 4] > 15]
print(yrs_active)

[[    7 39000   480  1700    18]
 [    9 45000   550  1800    25]
 [    4 41000   500  1600    20]]


In [76]:
# Q14.4: Calculate the total time all customers have been active (in years)
total_active_time = np.sum(banking_data[:, 4])
print(total_active_time)

142


In [77]:
# Q14.5: Find the customer with the shortest time active
customer_short_active= np.argmin(banking_data[:, 4])
shortest_customer_active = banking_data[customer_short_active]
print(f"customer ID: {customer_short_active}, Days: {shortest_customer_active}")

customer ID: 0, Days: [    3 28000   380  1100     8]


### Question 15: Advanced Array Operations

In [78]:
# Q15.1: Apply a function to calculate 5% interest on all account balances
import numpy as np
def add_interest(balance):
  balance * 1.05
interest_applied = np.vectorize(add_interest)(banking_data[:,1])
print(interest_applied)

[None None None None None None None None None None]


In [79]:
# Q15.2: Use np.where to categorize customers by balance ranges
balances = banking_data[:,1]
customers_balance =  np.where(balances < 15000, "Low",
              np.where(balances < 45000, "Medium", "High"))
print(customers_balance)

['Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'High'
 'Medium' 'Medium']


In [80]:
# Q15.3: Use np.select to categorize customers by credit score ranges
conditions = [
    banking_data[:, 4] < 9,
    (banking_data[:, 4] >= 15) & (banking_data[:, 4] < 20),
    banking_data[:, 4] >= 20
]
choices = ['poor', 'Mid-range', 'good']
cus_credit_score = np.select(conditions, choices, default='Unknown')
print(cus_credit_score)

['poor' 'Unknown' 'Mid-range' 'Mid-range' 'Unknown' 'Unknown' 'Unknown'
 'good' 'good' 'Unknown']


In [81]:
# Q15.4: Use np.piecewise to apply different interest rates based on balance
def low_interest(x): return x * 1.05
def mid_interest(x): return x * 1.10
def high_interest(x): return x * 1.20

interest_prices = np.piecewise(
    banking_data[:, 1],
    [banking_data[:, 1] < 20000, (banking_data[:, 1] >= 20000) & (banking_data[:, 1] < 25000), banking_data[:, 1] >= 25000],
    [low_interest, mid_interest, high_interest]
)
print(interest_prices)

[33600 39600 38400 46800 30000 36000 32400 54000 49200 42000]


In [82]:
# Q15.5: Use np.apply_along_axis to calculate the sum of each row
row_sums = np.apply_along_axis(np.sum, 1, banking_data)
print(row_sums)

[29491 34881 33967 41205 26511 31672 28675 47384 43124 36837]


### Question 16: Array Concatenation and Stacking

In [83]:
# Q16.1: Concatenate two arrays horizontally using np.hstack()
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
con_array = np.hstack([array1,array2])
print(con_array)

[1 2 3 4 5 6]


In [84]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
vcon_array = np.vstack([array1,array2])
print(vcon_array)

[[1 2 3]
 [4 5 6]]


In [85]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
import numpy as np
data = np.concatenate([array1,array2],axis = 0)
print(data)

[1 2 3 4 5 6]


In [86]:
# Q16.4: Stack arrays depth-wise using np.dstack()
data = np.dstack([array1,array2])
print(data)

[[[1 4]
  [2 5]
  [3 6]]]


In [87]:
# Q16.5: Create a column stack using np.column_stack()
data = np.column_stack([array1,array2])
print(data)

[[1 4]
 [2 5]
 [3 6]]


### Question 17: Array Splitting Operations

In [88]:
# Q17.1: Split an array into 3 equal parts using np.split()
array = np.array([1,2,3,4,5,6])
split_array = np.split(array,3)
for i, part in enumerate(split_array):
  print(f"Parts[{i+1}] = {part} ")

Parts[1] = [1 2] 
Parts[2] = [3 4] 
Parts[3] = [5 6] 


In [89]:
# Q17.2: Split an array at specific indices using np.split()
array = np.array([1,2,3,4,5,6])
split_array = np.split(array,[2,8])
print(split_array)

[array([1, 2]), array([3, 4, 5, 6]), array([], dtype=int64)]


In [90]:
# Q17.3: Split an array horizontally using np.hsplit()
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_parts = np.hsplit(arr_2d, 3)
print(hsplit_parts)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [91]:
# Q17.4: Split an array vertically using np.vsplit()
vsplit_parts = np.vsplit(arr_2d, 2)
print(f"Vertical parts:{vsplit_parts}")

Vertical parts:[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [92]:
# Q17.5: Split an array into equal chunks using np.array_split()
chunks = np.array_split(array, 4)
print(f"Split into 4 chunks:{chunks}")

Split into 4 chunks:[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Question 18: Array Repetition and Tiling

In [93]:
# Q18.1: Repeat each element of an array 3 times using np.repeat()
import numpy as np
elements = np.repeat(array1,3)
print(elements)

[1 1 1 2 2 2 3 3 3]


In [94]:
# Q18.2: Repeat an entire array 2 times using np.tile()
elements = np.tile(array1,2)
print(elements)

[1 2 3 1 2 3]


In [95]:
# Q18.3: Repeat a 2D array using np.tile()
arr_2d_small = np.array([[1, 2], [3, 4]])
tiled_2d = np.tile(arr_2d_small, (2, 3))
print(tiled_2d)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [96]:
# Q18.4: Create a pattern using np.tile()
pattern = np.array([1, 0])
pattern_tiled = np.tile(pattern, 5)
print(pattern_tiled)

[1 0 1 0 1 0 1 0 1 0]


In [97]:
# Q18.5: Repeat elements with different counts using np.repeat()
repeat_counts = [2, 1, 3]
repeated_variable = np.repeat(array1, repeat_counts)
print(repeated_variable)

[1 1 2 3 3 3]


### Question 19: Array Comparison and Logical Operations

In [98]:
# Q19.1: Compare two arrays for equality using np.array_equal()
out_comparision = np.array_equal(array1, array2)
print(out_comparision)

False


In [99]:
# Q19.2: Check if arrays are close using np.allclose()
close_comparision = np.allclose(array1, array2)
print(close_comparision)

False


In [100]:
# Q19.3: Apply logical AND operation between arrays
out_comparision = np.logical_and(array1>1, array2>4)
print(out_comparision)


[False  True  True]


In [101]:
# Q19.4: Apply logical OR operation between arrays
logical_or = np.logical_or(array1 == 1, array2 == 3)
print(logical_or)

[ True False False]


In [102]:
# Q19.5: Apply logical NOT operation to an array
logical_not = np.logical_not(array1 == 1)
print(logical_not)

[False  True  True]



### Question 20: Array Set Operations

In [103]:
# Q20.1: Find unique elements in an array using np.unique()
array = np.array([1,1,3,2,5,3,5,5,7])
unique_ele = np.unique([array])
print(unique_ele)

[1 2 3 5 7]


In [104]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()
intersection_ele = np.intersect1d(array1,array2)
print(intersection_ele)

[]


In [105]:
# Q20.3: Find the union of two arrays using np.union1d()
union_ele = np.union1d(array1,array2)
print(union_ele)

[1 2 3 4 5 6]


In [106]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
ele_1st_notin_2nd = np.setdiff1d(array1,array2)
print(ele_1st_notin_2nd)

[1 2 3]


In [108]:
# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
symmetric_diff = np.setxor1d(array1,array2)
print(symmetric_diff)

[1 2 3 4 5 6]
